export const enTextResources = {
  airQuality: "Air quality",
  airQualityLevel: "Air quality level",
  anErrorOccured: "An error occured",
  appName: "Szpek.pl",
  bad: "Bad",
  cancel: "Cancel",
  comments: "Comments",
  contact: "Contact",
  contactInfo: "The most convenient way to contact us is to write a message on the Szpek.pl funpage on Facebook -> ",
  contactInfo2: "Or write an email to",
  currentAirQuality: "Current air quality",
  dashboard: "Dashboard",
  email: "Email",
  emailHasBeenSended: "Email has been sended",
  enterAValidEmailFormat: "Enter a valid email format",
  exit: "Exit",
  faq: "Faq",
  forgetPassword: "Forget password",
  frequentlyAskedQuestions: "Frequently asked questions",
  good: "Good",
  iAccept: "I Accept",
  ifYouHaveEnteredTheCorrectEmailWeSendLinkToResetThePassword: "If you have entered the correct email, we send a link to reset the password",
  last24hours: "Last 24 hours",
  legend: "Legend",
  legendInfo: "The table shows the air level corresponding to the level of smog in the air. The intervals are closed on the left side. Information of air quality levels comes from the Polish Inspectorate for Environmental Protection",
  logIn: "Log in",
  logOut: "Log out",
  map: "Map",
  mapOfQualityConditionAndAirPollution: "Map of quality, condition and air pollution",
  maximumNumberOfCharactersIs: "Maximum number of characters is",
  measurementError: "Measurement error",
  minimumNumberOfCharactersIs: "Minimum number of characters is",
  moreDetails: "More details",
  moreInfo: "More info",
  newPassword: "New password",
  noLocationOnTheList: "If the location is not on the list, it means that the sensor has not sent any data within the last 24 hours",
  nowYouCanLogIn: "Now you can log in",
  ok: "Ok",
  password: "Password",
  passwordChanged: "Password changed",
  passwordMustHaveAtLeastOneNumberUppercaseLetterLowercaseLetterAndSpecialCharacter: "Password must have at least one number, uppercase letter, lowercase letter and special character",
  passwordsMustBeTheSame: "Passwords must be the same",
  poor: "Poor",
  qualityAndConditionOfAirPollutionInYourTown: "The quality and condition of air pollution in your town",
  repeatNewPassword: "Repeat new password",
  resetPassword: "Reset password",
  returnToTheLogInPage: "Return to the log in page",
  returnToTheMainPage: "Return to the main page",
  send: "Send",
  soon: "Soon",
  theLegendOfAirQualityConditionAndPollution: "The legend of air quality, condition and pollution",
  thereAreNoActiveLocations: "There are no active locations",
  thisFieldIsRequired: "This field is required",
  thisWebsiteUsesCookiesForStatisticalPurposes: "This website uses cookies for statistical purposes",
  tryAgainLater: "Try again later",
  unableToConnectToTheServer: "Unable to connect to the server",
  usernameOrEmail: "Username or email",
  veryBad: "Very Bad",
  veryGood: "Very good",
  whoIAm: "I am {{name}}"
}
