export const plTextResources = {
  airQuality: "Jakość powietrza",
  airQualityLevel: "Poziom jakości powietrza",
  anErrorOccured: "Wystąpił błąd",
  appName: "Szpek.pl",
  bad: "Zła",
  cancel: "Anuluj",
  comments: "Komentarze",
  contact: "Kontakt",
  contactInfo: "Najlepiej skontaktować się z nami przez wiadomość na funpage Szpek.pl na facebooku -> ",
  contactInfo2: "Lub też napisać mail na adres",
  currentAirQuality: "Aktualna jakość powietrza",
  dashboard: "Dashboard",
  email: "Email",
  emailHasBeenSended: "Email został wysłany",
  enterAValidEmailFormat: "Podaj poprawny format email",
  exit: "Wyjdź",
  faq: "Faq",
  forgetPassword: "Zapomniałeś hasła",
  frequentlyAskedQuestions: "Najczęściej zadawane pytania",
  good: "Dobra",
  iAccept: "Akceptuje",
  ifYouHaveEnteredTheCorrectEmailWeSendLinkToResetThePassword: "Jeśli podałeś poprawny email, wyślemy na niego link do restartu hasła",
  last24hours: "Ostatnie 24 godziny",
  legend: "Legenda",
  legendInfo: "Tabela przedstawia stan powietrza odpowiadający poziomowi smogu w powietrzu. Przedziały są lewostronnie domknięte. Informacje o poziomach jakości powietrza pochodzą ze strony Polskiej Inspekcji Ochorny Środowiska",
  logIn: "Zaloguj się",
  logOut: "Wyloguj się",
  map: "Mapa",
  mapOfQualityConditionAndAirPollution: "Mapa jakości, stanu i zanieczyszczenia powietrza",
  maximumNumberOfCharactersIs: "Maksymalna liczba znaków wynosi",
  measurementError: "Błąd pomiaru",
  minimumNumberOfCharactersIs: "Minimalna liczba znaków wynosi",
  moreDetails: "Szczegóły",
  moreInfo: "Więcej informacji",
  newPassword: "Nowe hasło",
  noLocationOnTheList: "Jeśli lokalizacji nie ma na liście to znaczy, że sensor nie wysłał żadnych danych w ciągu ostatnich 24 godzin",
  nowYouCanLogIn: "Teraz możesz się zalogować",
  ok: "Umiarkowana",
  password: "Hasło",
  passwordChanged: "Hasło zmienione",
  passwordMustHaveAtLeastOneNumberUppercaseLetterLowercaseLetterAndSpecialCharacter: "Hasło musi mieć przynajmniej jedną cyfrę, wielką, małą litere i znak specjalny",
  passwordsMustBeTheSame: "Hasła muszą być takie same",
  poor: "Dostateczna",
  qualityAndConditionOfAirPollutionInYourTown: "Jakość i stan zanieczyszczenia powietrza w twojej miejscowości",
  repeatNewPassword: "Powtórz nowe hasło",
  resetPassword: "Zresetuj hasło",
  returnToTheLogInPage: "Wróć do strony logowania",
  returnToTheMainPage: "Wróć do strony głównej",
  send: "Wyślij",
  soon: "Wkrótce",
  theLegendOfAirQualityConditionAndPollution: "Legenda jakości, stanu i zanieczyszczenia powietrza",
  thereAreNoActiveLocations: "Brak aktywnych lokalizacji",
  thisFieldIsRequired: "To pole jest wymagane",
  thisWebsiteUsesCookiesForStatisticalPurposes: "Niniejsza strona wykorzystuje pliki cookies w celach statystycznych",
  tryAgainLater: "Spróbuj ponownie później",
  unableToConnectToTheServer: "Nie można połączyć się z serwerem",
  usernameOrEmail: "Nazwa użytkownika lub email",
  veryBad: "Bardzo zła",
  veryGood: "Bardzo dobra",
  whoIAm: "Jestem {{name}}"
}
