services:
  web:
    build:
      context: szpek
      target: dev-envs
      #dev-envs - local machine
      #builder - production
    ports:
      - 4200:4200
    volumes:
      - ./szpek:/project
      - /project/node_modules
