export const textResources = {
  'en-US': {
    airQuality: "Air quality",
    airQualityLevel: "Air quality level",
    anErrorOccured: "An error occured",
    appName: "Szpek.pl",
    bad: "Bad",
    cancel: "Cancel",
    comments: "Comments",
    contact: "Contact",
    contactInfo: "The most convenient way to contact us is to write a message on the Szpek.pl funpage on Facebook. The link to it is located on the sidebar",
    currentAirQuality: "Current air quality",
    email: "Email",
    emailHasBeenSended: "Email has been sended",
    enterAValidEmailFormat: "Enter a valid email format",
    exit: "Exit",
    faq: "Faq",
    forgetPassword: "Forget password",
    frequentlyAskedQuestions: "Frequently asked questions",
    good: "Good",
    iAccept: "I Accept",
    ifYouHaveEnteredTheCorrectEmailWeSendLinkToResetThePassword: "If you have entered the correct email, we send a link to reset the password",
    last24hours: "Last 24 hours",
    legend: "Legend",
    legendInfo: "The table shows the air level corresponding to the level of smog in the air. The compartments are closed on the left side. Information on air quality levels comes from the Polish Environmental Protection Inspectorate",
    likeUsOnFacebook: "Like us on Facebook",
    logIn: "Log in",
    logOut: "Log out",
    map: "Map",
    mapOfQualityConditionAndAirPollution: "Map of quality, condition and air pollution",
    maximumNumberOfCharactersIs: "Maximum number of characters is",
    measurementError: "Measurement error",
    minimumNumberOfCharactersIs: "Minimum number of characters is",
    moreDetails: "More details",
    moreInfo: "More info",
    newPassword: "New password",
    noLocationOnTheList: "If the location is not on the list, it means that the sensor has not sent any data within the last 24 hours",
    nowYouCanLogIn: "Now you can log in",
    ok: "Ok",
    password: "Password",
    passwordChanged: "Password changed",
    passwordMustHaveAtLeastOneNumberUppercaseLetterLowercaseLetterAndSpecialCharacter: "Password must have at least one number, uppercase letter, lowercase letter and special character",
    passwordsMustBeTheSame: "Passwords must be the same",
    poor: "Poor",
    qualityAndConditionOfAirPollutionInYourTown: "The quality and condition of air pollution in your town",
    repeatNewPassword: "Repeat new password",
    resetPassword: "Reset password",
    returnToTheLogInPage: "Return to the log in page",
    returnToTheMainPage: "Return to the main page",
    send: "Send",
    soon: "Soon",
    theLegendOfAirQualityConditionAndPollution: "The legend of air quality, condition and pollution",
    thereAreNoActiveLocations: "There are no active locations",
    thisFieldIsRequired: "This field is required",
    thisWebsiteUsesCookiesForStatisticalPurposes: "This website uses cookies for statistical purposes",
    tryAgainLater: "Try again later",
    unableToConnectToTheServer: "Unable to connect to the server",
    username: "Username",
    veryBad: "Very Bad",
    veryGood: "Very good",
    whoIAm: "I am {{name}}"
  },
  'pl-PL': {
    airQuality: "Jakość powietrza",
    airQualityLevel: "Poziom jakości powietrza",
    anErrorOccured: "Wystąpił błąd",
    appName: "Szpek.pl",
    bad: "Zła",
    cancel: "Anuluj",
    comments: "Komentarze",
    contact: "Kontakt",
    contactInfo: "Najwygodniej skontaktować się z nami przez napisanie wiadomości na funpage Szpek.pl na facebooku. Link do niego znajduje się na pasku",
    currentAirQuality: "Aktualna jakość powietrza",
    email: "Email",
    emailHasBeenSended: "Email został wysłany",
    enterAValidEmailFormat: "Podaj poprawny format email",
    exit: "Wyjdź",
    faq: "Faq",
    forgetPassword: "Zapomniałeś hasła",
    frequentlyAskedQuestions: "Najczęściej zadawane pytania",
    good: "Dobra",
    iAccept: "Akceptuje",
    ifYouHaveEnteredTheCorrectEmailWeSendLinkToResetThePassword: "Jeśli podałeś poprawny email, wyślemy na niego link do restartu hasła",
    last24hours: "Ostatnie 24 godziny",
    legend: "Legenda",
    legendInfo: "Tabela przedstawia stan powietrza odpowiadający poziomowi smogu w powietrzu. Przedziały są lewostronnie domknięte. Informacje o poziomach jakości powietrza pochodzą ze strony Polskiej Inspekcji Ochorny Środowiska",
    likeUsOnFacebook: "Polub nas na Facebooku",
    logIn: "Zaloguj się",
    logOut: "Wyloguj się",
    map: "Mapa",
    mapOfQualityConditionAndAirPollution: "Mapa jakości, stanu i zanieczyszczenia powietrza",
    maximumNumberOfCharactersIs: "Maksymalna liczba znaków wynosi",
    measurementError: "Błąd pomiaru",
    minimumNumberOfCharactersIs: "Minimalna liczba znaków wynosi",
    moreDetails: "Szczegóły",
    moreInfo: "Więcej informacji",
    newPassword: "Nowe hasło",
    noLocationOnTheList: "Jeśli lokalizacji nie ma na liście to znaczy, że sensor nie wysłał żadnych danych w ciągu ostatnich 24 godzin",
    nowYouCanLogIn: "Teraz możesz się zalogować",
    ok: "Umiarkowana",
    password: "Hasło",
    passwordChanged: "Hasło zmienione",
    passwordMustHaveAtLeastOneNumberUppercaseLetterLowercaseLetterAndSpecialCharacter: "Hasło musi mieć przynajmniej jedną cyfrę, wielką, małą litere i znak specjalny",
    passwordsMustBeTheSame: "Hasła muszą być takie same",
    poor: "Dostateczna",
    qualityAndConditionOfAirPollutionInYourTown: "Jakość i stan zanieczyszczenia powietrza w twojej miejscowości",
    repeatNewPassword: "Powtórz nowe hasło",
    resetPassword: "Zresetuj hasło",
    returnToTheLogInPage: "Wróć do strony logowania",
    returnToTheMainPage: "Wróć do strony głównej",
    send: "Wyślij",
    soon: "Wkrótce",
    theLegendOfAirQualityConditionAndPollution: "Legenda jakości, stanu i zanieczyszczenia powietrza",
    thereAreNoActiveLocations: "Brak aktywnych lokalizacji",
    thisFieldIsRequired: "To pole jest wymagane",
    thisWebsiteUsesCookiesForStatisticalPurposes: "Niniejsza strona wykorzystuje pliki cookies w celach statystycznych",
    tryAgainLater: "Spróbuj ponownie później",
    unableToConnectToTheServer: "Nie można połączyć się z serwerem",
    username: "Nazwa użytkownika",
    veryBad: "Bardzo zła",
    veryGood: "Bardzo dobra",
    whoIAm: "Jestem {{name}}"
  }
};
