export const plTextResources = {
  address: "Adres",
  adminPanel: "Panel administracyjny",
  airQuality: "Jakość powietrza",
  airQualityLevel: "Poziom jakości powietrza",
  anErrorOccured: "Wystąpił błąd",
  appName: "Szpek.pl",
  bad: "Zła",
  cancel: "Anuluj",
  city: "Miasto",
  company: "Firma",
  contact: "Kontakt",
  contactInfo: "Najlepiej skontaktować się z nami przez wiadomość na funpage Szpek.pl na facebooku -> ",
  contactInfo2: "Lub też napisać mail na adres",
  countryCode: "Kod kraju",
  currentAirQuality: "Aktualna jakość powietrza",
  currentLocation: "Aktualna lokalizacja",
  dashboard: "Dashboard",
  dateOfMeasurement: "Data pomiaru",
  email: "Email",
  emailHasBeenSended: "Email został wysłany",
  enterAValidEmailFormat: "Podaj poprawny format email",
  exit: "Wyjdź",
  faq: "Faq",
  forgetPassword: "Zapomniałeś hasła",
  frequentlyAskedQuestions: "Najczęściej zadawane pytania",
  good: "Dobra",
  heightAboveSeaLevel: "Wysokość nad poziomem morza",
  humidity: "Wilgotność",
  iAccept: "Akceptuje",
  ifYouHaveEnteredTheCorrectEmailWeSendLinkToResetThePassword: "Jeśli podałeś poprawny email, wyślemy na niego link do restartu hasła",
  last24hours: "Ostatnie 24 godziny",
  latitude: "Szerokość geograficzna",
  legend: "Legenda",
  legendInfo: "Tabela przedstawia stan powietrza odpowiadający poziomowi smogu w powietrzu. Przedziały są lewostronnie domknięte. Informacje o poziomach jakości powietrza pochodzą ze strony Polskiej Inspekcji Ochorny Środowiska",
  logIn: "Zaloguj się",
  logOut: "Wyloguj się",
  longitude: "Długość geograficzna",
  manual: "Instrukcja",
  map: "Mapa",
  mapOfQualityConditionAndAirPollution: "Mapa jakości, stanu i zanieczyszczenia powietrza",
  maximumNumberOfCharactersIs: "Maksymalna liczba znaków wynosi",
  measurementError: "Błąd pomiaru",
  measurementHistory: "Historia pomiarów",
  minimumNumberOfCharactersIs: "Minimalna liczba znaków wynosi",
  moreDetails: "Szczegóły",
  moreInfo: "Więcej informacji",
  mySensors: "Moje czujniki",
  name: "Imie",
  newPassword: "Nowe hasło",
  noMeasurementsOnThisDay: "Brak pomiarów w tym dniu",
  noLocationOnTheList: "Jeśli lokalizacji nie ma na liście to znaczy, że sensor nie wysłał żadnych danych w ciągu ostatnich 24 godzin",
  noWeatherConditionsMeasurementsForThisSensor: "Brak pomiarów warunków atmosferycznych dla tego czujnika",
  nowYouCanLogIn: "Teraz możesz się zalogować",
  ok: "Umiarkowana",
  password: "Hasło",
  passwordChanged: "Hasło zmienione",
  passwordMustHaveAtLeastOneNumberUppercaseLetterLowercaseLetterAndSpecialCharacter: "Hasło musi mieć przynajmniej jedną cyfrę, wielką, małą litere i znak specjalny",
  passwordsMustBeTheSame: "Hasła muszą być takie same",
  pM10Quality: "Jakość PM10",
  pM10Value: "Wartość PM10",
  pM1Value: "Wartość PM1",
  pM25Quality: "Jakość PM2.5",
  pM25Value: "Wartość PM2.5",
  poor: "Dostateczna",
  postCode: "Kod pocztowy",
  pressure: "Ciśnienie",
  private: "Prywatny",
  qualityAndConditionOfAirPollutionInYourTown: "Jakość i stan zanieczyszczenia powietrza w twojej miejscowości",
  repeatNewPassword: "Powtórz nowe hasło",
  resetPassword: "Zresetuj hasło",
  returnToTheLogInPage: "Wróć do strony logowania",
  returnToTheMainPage: "Wróć do strony głównej",
  send: "Wyślij",
  sensorCode: "Kod czujnika",
  sensorLocation: "Lokalizacja czujnika",
  sensorOwner: "Właściciel czujników",
  soon: "Wkrótce",
  street: "Ulica",
  temperature: "Temperatura",
  theLegendOfAirQualityConditionAndPollution: "Legenda jakości, stanu i zanieczyszczenia powietrza",
  thereAreNoActiveLocations: "Brak aktywnych lokalizacji",
  thisFieldIsRequired: "To pole jest wymagane",
  thisWebsiteUsesCookiesForStatisticalPurposes: "Niniejsza strona wykorzystuje pliki cookies w celach statystycznych",
  tryAgainLater: "Spróbuj ponownie później",
  unableToConnectToTheServer: "Nie można połączyć się z serwerem",
  usernameOrEmail: "Nazwa użytkownika lub email",
  veryBad: "Bardzo zła",
  veryGood: "Bardzo dobra",
  voivodeship: "Województwo",
  weatherConditions: "Warunki atmosferyczne",
  whoIAm: "Jestem {{name}}"
}
